# Python for Data Science // S.4 // Numpy // PYTN-KS09
---

In [2]:
import numpy as np

In [2]:
angka = [1, 2, 3]

In [3]:
angkanp = np.array(angka)

In [4]:
angkanp

array([1, 2, 3])

In [5]:
angka * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
angkanp * 3

array([3, 6, 9])

In [7]:
versilist = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
versilist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
versinumpy = np.array(versilist)
versinumpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((2, 4)) #Array 2 dimensi

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0, 8, 10) #membuat array dari 0 sampai 8, akan dipecah sebanyak 10 pecahan, dimana \
                      #jarak antar tiap pecahan itu sama besar
                      #array satu dimensi

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

## identify matrix

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
#bilangan distribusi uniform
np.random.rand(7)

array([0.02373306, 0.49416764, 0.08744657, 0.80536422, 0.30818563,
       0.99205839, 0.6030283 ])

In [22]:
#bilangan distribusi uniform 2 dimensi
np.random.rand(5, 4)

array([[0.40991158, 0.45322695, 0.92945083, 0.29734908],
       [0.88674361, 0.49254632, 0.42583464, 0.82261828],
       [0.26673014, 0.73386794, 0.01744532, 0.97465407],
       [0.0026449 , 0.77944545, 0.35497429, 0.488059  ],
       [0.21505581, 0.39719984, 0.70680279, 0.68840411]])

In [23]:
#bilangan distribusi normal (gaussian), dari -tak hingga sampai tak hingga
np.random.randn(10)

array([ 1.33104987, -3.47190095,  0.63689899, -2.40913154, -1.11832911,
        0.03147012,  1.14855367,  0.69360815,  0.64958357, -0.72140892])

In [24]:
#bilangan distribusi normal (gaussian) 2 dimensi
np.random.randn(4, 4)

array([[-0.26352304, -0.66112666,  0.58581741,  0.4064439 ],
       [-1.49072929,  1.27040082, -1.7418723 , -0.24084515],
       [ 0.10269437,  1.39069471, -0.22918999,  0.61481803],
       [ 1.44088738, -1.36234128, -0.00710141,  0.46851029]])

In [34]:
from numpy.random import rand, randn, randint

In [26]:
randn(6, 2)

array([[-0.92359767,  0.06636444],
       [-0.49468568,  1.05417949],
       [-0.11612129, -0.67363554],
       [-0.21055649, -0.49262304],
       [-0.79171091, -0.23419949],
       [ 0.07159664,  0.36553495]])

In [29]:
randint(0,10,5)  #bilangan array integer

array([5, 0, 1, 0, 1])

In [30]:
bilangan = randint(0,100,20)

In [31]:
bilangan

array([ 8, 62, 32, 65, 90, 82, 84, 16, 26, 11, 20,  8, 94, 85, 51, 69, 28,
       78, 13, 66])

In [32]:
bilangan.reshape(4,5) #mengubah menjadi matriks 2 dimensi
                      #ukuran baris kolom harus pecahan dari jumlah angka pada bilangan

array([[ 8, 62, 32, 65, 90],
       [82, 84, 16, 26, 11],
       [20,  8, 94, 85, 51],
       [69, 28, 78, 13, 66]])

In [33]:
bilangan.reshape(2,10)

array([[ 8, 62, 32, 65, 90, 82, 84, 16, 26, 11],
       [20,  8, 94, 85, 51, 69, 28, 78, 13, 66]])

In [35]:
randint(0, 3, 5)

array([1, 1, 2, 0, 0])

In [36]:
randint(0, 10, 25)

array([5, 1, 9, 4, 2, 3, 8, 3, 3, 8, 8, 5, 4, 5, 1, 3, 7, 1, 8, 3, 0, 0,
       9, 4, 3])

In [39]:
coba = randint(0, 10, 20).reshape(5, 4)

In [1]:
coba

NameError: name 'coba' is not defined

In [41]:
coba.reshape(2, 10)          #hanya menunjukan ilustrasi

array([[3, 3, 8, 7, 4, 0, 0, 1, 1, 7],
       [6, 3, 8, 1, 2, 8, 9, 3, 5, 3]])

In [42]:
coba

array([[3, 3, 8, 7],
       [4, 0, 0, 1],
       [1, 7, 6, 3],
       [8, 1, 2, 8],
       [9, 3, 5, 3]])

In [43]:
coba = coba.reshape(2, 10)

In [44]:
coba

array([[3, 3, 8, 7, 4, 0, 0, 1, 1, 7],
       [6, 3, 8, 1, 2, 8, 9, 3, 5, 3]])

In [45]:
coba1d = randint(0, 100, 20)

In [46]:
coba2d = randint(0, 100, 20).reshape(4, 5)

In [47]:
coba1d

array([51, 47, 63, 18, 38, 60, 21, 63, 34, 80, 56, 38, 54, 12, 49, 59, 18,
       62, 30, 75])

In [48]:
coba2d

array([[72, 46, 45,  4, 88],
       [16,  6,  9, 15, 42],
       [55, 50, 31,  5, 17],
       [13, 19, 69, 30, 89]])

In [49]:
coba1d.max()

80

In [51]:
coba2d.max()

89

In [52]:
coba1d.min()

12

In [53]:
coba2d.min()

4

In [54]:
coba1d.argmax() #untuk mengetahui indeks ke berapa menunjukan angka paling besar

9

In [55]:
coba2d.argmax() #untuk mengetahui indeks ke berapa menunjukan angka paling besar

19

In [56]:
coba1d.argmin() #untuk mengetahui indeks ke berapa menunjukan angka paling kecil

13

In [57]:
coba2d.argmin() #untuk mengetahui indeks ke berapa menunjukan angka paling kecil

3

In [58]:
coba1d.shape

(20,)

In [61]:
coba2d.shape #tidak memakai tanda kurung karena hanya memanggil fungsi
             # untuk mengetahui ukuran matriks

(4, 5)

In [63]:
coba1d.dtype # untuk mengetahui tipe data

dtype('int32')

In [64]:
coba2d.dtype # untuk mengetahui tipe data

dtype('int32')

## Indexing di NumPy

In [65]:
import numpy as np

In [67]:
coba = np.arange(0,11)

In [68]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
coba[6] # mengambil indeks ke-6

6

In [70]:
coba[5:]

array([ 5,  6,  7,  8,  9, 10])

In [71]:
coba[5:9]

array([5, 6, 7, 8])

In [72]:
coba[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
coba2 = coba[:6]

In [74]:
coba2

array([0, 1, 2, 3, 4, 5])

In [75]:
coba2[:] = 100

In [76]:
coba2

array([100, 100, 100, 100, 100, 100])

## perlu latihan lagi

In [78]:
coba2 = coba.copy #agar tidak mengubah nilai pada variabel

In [77]:
coba

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [84]:
coba

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [85]:
coba2 = coba[:6]

In [86]:
coba2

array([100, 100, 100, 100, 100, 100])

In [87]:
coba2[:] = 200

In [88]:
coba2

array([200, 200, 200, 200, 200, 200])

In [89]:
coba

array([200, 200, 200, 200, 200, 200,   6,   7,   8,   9,  10])

In [96]:
bil2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [97]:
bil2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
bil2d[0][0] #diikuti dengan baris ke berapa dan kolom ke berapa
            # cara indeks

1

In [101]:
bild2d[1] #menyatakan indeks baris

array([4, 5, 6])

In [102]:
bil2d[2][2]

9

## Slicing NumPy yang direkomendasikan

In [103]:
bil2d[2, 2]

9

In [104]:
bil2d[0, 0]

1

In [105]:
bil2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
bil2d[1:2,1:]

array([[5, 6]])

In [108]:
bil2d[1:2,1:]

array([[5, 6]])

## Slicing dengan Boolean di NumPy

In [109]:
bil = np.arange(1,11)

In [110]:
bil

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
angkaT = bil > 5

In [112]:
angkaT

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [114]:
bil = bil[angkaT]

In [115]:
bil

array([ 6,  7,  8,  9, 10])

In [116]:
bil = np.arange(1,11)

In [117]:
bil

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
bil[bil>5]

array([ 6,  7,  8,  9, 10])

In [119]:
bil

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
bil = bil[bil>5]

In [121]:
bil

array([ 6,  7,  8,  9, 10])

In [3]:
import numpy as np
xnb = np.array([1,2,3,4,5,6]).reshape(3, 2)
xnb

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
np.linspace(0,100, 5)

array([  0.,  25.,  50.,  75., 100.])

## Array Multidimensi

In [3]:
students_gpas = np.array([
    [4.0, 3.3, 3.5, 4.0], 
    [3.96, 3.92, 4.0, 4.0], 
    [3.2, 3.8, 4.0, 4.0]
], np.float16)
students_gpas

array([[4.  , 3.3 , 3.5 , 4.  ],
       [3.96, 3.92, 4.  , 4.  ],
       [3.2 , 3.8 , 4.  , 4.  ]], dtype=float16)

In [4]:
students_gpas.ndim #untuk mengetahui number of dimension

2

In [5]:
students_gpas.shape #menunjukkan banyaknya baris dan kolom

(3, 4)

In [6]:
students_gpas[2]

array([3.2, 3.8, 4. , 4. ], dtype=float16)

In [7]:
students_gpas[2, 3]

4.0

## Study Log MultiDimensi

In [8]:
study_minutes = np.zeros(100)

In [9]:
study_minutes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.uint16)
])
study_minutes.shape

(2, 100)

In [11]:
rand = np.random.RandomState(46)
fake_log = rand.randint(30, 180, size=100, dtype=np.uint16)
fake_log

array([ 99,  45,  70, 162, 146,  70, 177, 176,  47, 148, 123,  67,  90,
       122,  34, 160, 135, 102,  62,  61,  85,  52, 153, 128,  89,  37,
       109,  60, 128,  57, 160,  67, 144,  97, 150, 148,  32, 155, 116,
       137,  49,  70, 159, 159,  84, 114,  93, 110,  81, 122, 103,  53,
        52, 147,  75,  93,  45,  46, 177,  91,  70,  69,  46, 150,  86,
       170, 174, 143,  88,  71, 132,  67, 157, 118,  91, 158, 178, 176,
        37, 155,  45,  66,  60,  35, 154,  75,  53,  33,  80, 126,  76,
       113, 148, 163,  57,  83, 145, 148, 167, 129], dtype=uint16)

In [12]:
[fake_log[1], fake_log[21]]   #dalam list

[45, 52]

In [13]:
fake_log[[1, 21]]      #dalam array

array([45, 52], dtype=uint16)

In [14]:
index = np.array([
    [1, 21], [1,2]
])
fake_log[index]

array([[45, 52],
       [45, 70]], dtype=uint16)

In [15]:
practice = np.arange(42)
practice.shape = (7, 6)
practice

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [16]:
practice[2, 1]

13

In [17]:
practice[2:5]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [18]:
practice[2:5, 3]

array([15, 21, 27])

In [19]:
practice[2:5, 3:]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

In [20]:
practice_list = [1,2,3]
practice_list_copy = practice_list[:]
practice_list, practice_list_copy

([1, 2, 3], [1, 2, 3])

In [21]:
practice_list = [1,2,3]
practice_list_copy = practice_list[:]
practice_list, practice_list_copy
practice_list_copy[0] = 12345
practice_list, practice_list_copy

([1, 2, 3], [12345, 2, 3])

In [22]:
practice = np.arange(42)
practice.shape = (7, 6)
practice

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [23]:
not_copied = practice[:]
not_copied[0,0] = 12345
practice, not_copied

(array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]),
 array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]))

In [24]:
print(practice.base)

None


In [25]:
not_copied.base is practice #untuk mengetahui kebenaran base dari not_copied

True

In [26]:
study_minutes

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

## Filter Array dengan kondisi
### Mencari durasi belajar < 1 jam (60 menit)

In [27]:
fake_log

array([ 99,  45,  70, 162, 146,  70, 177, 176,  47, 148, 123,  67,  90,
       122,  34, 160, 135, 102,  62,  61,  85,  52, 153, 128,  89,  37,
       109,  60, 128,  57, 160,  67, 144,  97, 150, 148,  32, 155, 116,
       137,  49,  70, 159, 159,  84, 114,  93, 110,  81, 122, 103,  53,
        52, 147,  75,  93,  45,  46, 177,  91,  70,  69,  46, 150,  86,
       170, 174, 143,  88,  71, 132,  67, 157, 118,  91, 158, 178, 176,
        37, 155,  45,  66,  60,  35, 154,  75,  53,  33,  80, 126,  76,
       113, 148, 163,  57,  83, 145, 148, 167, 129], dtype=uint16)

In [28]:
rand = np.random.RandomState(46)
fake_log = rand.randint(30, 180, size=100, dtype=np.uint16)
fake_log

array([ 99,  45,  70, 162, 146,  70, 177, 176,  47, 148, 123,  67,  90,
       122,  34, 160, 135, 102,  62,  61,  85,  52, 153, 128,  89,  37,
       109,  60, 128,  57, 160,  67, 144,  97, 150, 148,  32, 155, 116,
       137,  49,  70, 159, 159,  84, 114,  93, 110,  81, 122, 103,  53,
        52, 147,  75,  93,  45,  46, 177,  91,  70,  69,  46, 150,  86,
       170, 174, 143,  88,  71, 132,  67, 157, 118,  91, 158, 178, 176,
        37, 155,  45,  66,  60,  35, 154,  75,  53,  33,  80, 126,  76,
       113, 148, 163,  57,  83, 145, 148, 167, 129], dtype=uint16)

In [29]:
fake_log < 60 #mencari nilai yang kurang dari 60
fake_log[fake_log < 60] #untuk mengetahui nilai apa saja yang kurang dari < 60

array([45, 47, 34, 52, 37, 57, 32, 49, 53, 52, 45, 46, 46, 37, 45, 35, 53,
       33, 57], dtype=uint16)

In [30]:
results = [] #mengetahui nilai yang kurang dari 60 dengan for loop
for value in fake_log:
    if value < 60:
        results.append(value)
    
np.array(results)

array([45, 47, 34, 52, 37, 57, 32, 49, 53, 52, 45, 46, 46, 37, 45, 35, 53,
       33, 57], dtype=uint16)

In [31]:
study_minutes = np.zeros(100, np.uint16)
study_minutes = np.append(study_minutes, [fake_log])
study_minutes

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  99,  45,  70, 162,
       146,  70, 177, 176,  47, 148, 123,  67,  90, 122,  34, 160, 135,
       102,  62,  61,  85,  52, 153, 128,  89,  37, 109,  60, 128,  57,
       160,  67, 144,  97, 150, 148,  32, 155, 116, 137,  49,  70, 159,
       159,  84, 114,  93, 110,  81, 122, 103,  53,  52, 147,  75,  93,
        45,  46, 177,  91,  70,  69,  46, 150,  86, 170, 174, 143,  88,
        71, 132,  67, 157, 118,  91, 158, 178, 176,  37, 155,  4

In [32]:
study_minutes[study_minutes < 60]
study_minutes[(study_minutes < 60) & (study_minutes > 0)]

array([45, 47, 34, 52, 37, 57, 32, 49, 53, 52, 45, 46, 46, 37, 45, 35, 53,
       33, 57], dtype=uint16)

## Aljabar Linear

In [33]:
orders = np.array([[2, 0, 0, 0], [1, 0, 2, 4], [1, 2, 1, 0], [4, 6, 0, 2]])
totals = np.array([20000, 32000, 20000, 61000])
prices = np.linalg.solve(orders, totals)
prices

array([10000.,  2500.,  5000.,  3000.])

In [34]:
orders @ prices #operasi perkalian pada numpy

array([20000., 32000., 20000., 61000.])

## Fungsi Universal

In [35]:
a, b = np.split(np.arange(1, 11), 2)
a, b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [36]:
a + b

array([ 7,  9, 11, 13, 15])

In [37]:
a * b

array([ 6, 14, 24, 36, 50])

In [38]:
a - b

array([-5, -5, -5, -5, -5])

In [39]:
a + np.repeat(3 ,5)

array([4, 5, 6, 7, 8])

In [40]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
x1, x2

(array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]),
 array([0., 1., 2.]))

In [41]:
np.add(x1, x2) #menambahkan array x1 dengan array x2

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [42]:
np.add(x1, 2) #menambahkan array x1 dengan 2

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

## Operasi Matrix Lainnya

In [43]:
study_less = study_minutes[(study_minutes < 60) & (study_minutes > 0)]
print(study_less)
np.add.reduce(study_less) # menjumlahkan semua elemen yang ada pada variabel study_less

[45 47 34 52 37 57 32 49 53 52 45 46 46 37 45 35 53 33 57]


855

In [44]:
np.sum(study_less) #menjumlahkan semua elemen yang ada pada variabel study_less

855

In [45]:
np.sum(study_minutes)

10415